app:
  title : shopping project

server:
  port: 9000


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  jap:
    database:mysql
    hibernate:
      ddl-auto: create
      properties:
      hibernate :
      show_sql : true
